/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* myUART_rx */
#define myUART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define myUART_rx_0_INBUF_ENABLED 1u
#define myUART_rx_0_INIT_DRIVESTATE 1u
#define myUART_rx_0_INIT_MUXSEL 18u
#define myUART_rx_0_INPUT_SYNC 2u
#define myUART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define myUART_rx_0_NUM 0u
#define myUART_rx_0_PORT GPIO_PRT5
#define myUART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define myUART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define myUART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define myUART_rx_INBUF_ENABLED 1u
#define myUART_rx_INIT_DRIVESTATE 1u
#define myUART_rx_INIT_MUXSEL 18u
#define myUART_rx_INPUT_SYNC 2u
#define myUART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define myUART_rx_NUM 0u
#define myUART_rx_PORT GPIO_PRT5
#define myUART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define myUART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* myUART_tx */
#define myUART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define myUART_tx_0_INBUF_ENABLED 0u
#define myUART_tx_0_INIT_DRIVESTATE 1u
#define myUART_tx_0_INIT_MUXSEL 18u
#define myUART_tx_0_INPUT_SYNC 2u
#define myUART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define myUART_tx_0_NUM 1u
#define myUART_tx_0_PORT GPIO_PRT5
#define myUART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define myUART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define myUART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define myUART_tx_INBUF_ENABLED 0u
#define myUART_tx_INIT_DRIVESTATE 1u
#define myUART_tx_INIT_MUXSEL 18u
#define myUART_tx_INPUT_SYNC 2u
#define myUART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define myUART_tx_NUM 1u
#define myUART_tx_PORT GPIO_PRT5
#define myUART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define myUART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* sdSPI_ss0_m */
#define sdSPI_ss0_m_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define sdSPI_ss0_m_0_INBUF_ENABLED 0u
#define sdSPI_ss0_m_0_INIT_DRIVESTATE 1u
#define sdSPI_ss0_m_0_INIT_MUXSEL 20u
#define sdSPI_ss0_m_0_INPUT_SYNC 2u
#define sdSPI_ss0_m_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sdSPI_ss0_m_0_NUM 3u
#define sdSPI_ss0_m_0_PORT GPIO_PRT12
#define sdSPI_ss0_m_0_SLEWRATE CY_GPIO_SLEW_FAST
#define sdSPI_ss0_m_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define sdSPI_ss0_m_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define sdSPI_ss0_m_INBUF_ENABLED 0u
#define sdSPI_ss0_m_INIT_DRIVESTATE 1u
#define sdSPI_ss0_m_INIT_MUXSEL 20u
#define sdSPI_ss0_m_INPUT_SYNC 2u
#define sdSPI_ss0_m_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sdSPI_ss0_m_NUM 3u
#define sdSPI_ss0_m_PORT GPIO_PRT12
#define sdSPI_ss0_m_SLEWRATE CY_GPIO_SLEW_FAST
#define sdSPI_ss0_m_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* sdSPI_miso_m */
#define sdSPI_miso_m_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define sdSPI_miso_m_0_INBUF_ENABLED 1u
#define sdSPI_miso_m_0_INIT_DRIVESTATE 1u
#define sdSPI_miso_m_0_INIT_MUXSEL 20u
#define sdSPI_miso_m_0_INPUT_SYNC 2u
#define sdSPI_miso_m_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sdSPI_miso_m_0_NUM 1u
#define sdSPI_miso_m_0_PORT GPIO_PRT13
#define sdSPI_miso_m_0_SLEWRATE CY_GPIO_SLEW_FAST
#define sdSPI_miso_m_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define sdSPI_miso_m_DRIVEMODE CY_GPIO_DM_HIGHZ
#define sdSPI_miso_m_INBUF_ENABLED 1u
#define sdSPI_miso_m_INIT_DRIVESTATE 1u
#define sdSPI_miso_m_INIT_MUXSEL 20u
#define sdSPI_miso_m_INPUT_SYNC 2u
#define sdSPI_miso_m_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sdSPI_miso_m_NUM 1u
#define sdSPI_miso_m_PORT GPIO_PRT13
#define sdSPI_miso_m_SLEWRATE CY_GPIO_SLEW_FAST
#define sdSPI_miso_m_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* sdSPI_mosi_m */
#define sdSPI_mosi_m_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define sdSPI_mosi_m_0_INBUF_ENABLED 0u
#define sdSPI_mosi_m_0_INIT_DRIVESTATE 1u
#define sdSPI_mosi_m_0_INIT_MUXSEL 20u
#define sdSPI_mosi_m_0_INPUT_SYNC 2u
#define sdSPI_mosi_m_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sdSPI_mosi_m_0_NUM 0u
#define sdSPI_mosi_m_0_PORT GPIO_PRT13
#define sdSPI_mosi_m_0_SLEWRATE CY_GPIO_SLEW_FAST
#define sdSPI_mosi_m_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define sdSPI_mosi_m_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define sdSPI_mosi_m_INBUF_ENABLED 0u
#define sdSPI_mosi_m_INIT_DRIVESTATE 1u
#define sdSPI_mosi_m_INIT_MUXSEL 20u
#define sdSPI_mosi_m_INPUT_SYNC 2u
#define sdSPI_mosi_m_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sdSPI_mosi_m_NUM 0u
#define sdSPI_mosi_m_PORT GPIO_PRT13
#define sdSPI_mosi_m_SLEWRATE CY_GPIO_SLEW_FAST
#define sdSPI_mosi_m_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* sdSPI_sclk_m */
#define sdSPI_sclk_m_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define sdSPI_sclk_m_0_INBUF_ENABLED 0u
#define sdSPI_sclk_m_0_INIT_DRIVESTATE 1u
#define sdSPI_sclk_m_0_INIT_MUXSEL 20u
#define sdSPI_sclk_m_0_INPUT_SYNC 2u
#define sdSPI_sclk_m_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sdSPI_sclk_m_0_NUM 2u
#define sdSPI_sclk_m_0_PORT GPIO_PRT12
#define sdSPI_sclk_m_0_SLEWRATE CY_GPIO_SLEW_FAST
#define sdSPI_sclk_m_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define sdSPI_sclk_m_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define sdSPI_sclk_m_INBUF_ENABLED 0u
#define sdSPI_sclk_m_INIT_DRIVESTATE 1u
#define sdSPI_sclk_m_INIT_MUXSEL 20u
#define sdSPI_sclk_m_INPUT_SYNC 2u
#define sdSPI_sclk_m_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sdSPI_sclk_m_NUM 2u
#define sdSPI_sclk_m_PORT GPIO_PRT12
#define sdSPI_sclk_m_SLEWRATE CY_GPIO_SLEW_FAST
#define sdSPI_sclk_m_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
