/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* sdSPI_SCB_IRQ */
#define sdSPI_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define sdSPI_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define sdSPI_SCB_IRQ__INTC_NUMBER 47u
#define sdSPI_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define sdSPI_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define sdSPI_SCB_IRQ_INTC_NUMBER 47u

/* myUART_SCB_IRQ */
#define myUART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define myUART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define myUART_SCB_IRQ__INTC_NUMBER 46u
#define myUART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define myUART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define myUART_SCB_IRQ_INTC_NUMBER 46u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
