/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* UART_SCB_IRQ */
#define UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ__INTC_NUMBER 46u
#define UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ_INTC_NUMBER 46u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr__INTC_CORTEXM0P_PRIORITY 3u
#define BLE_bless_isr__INTC_CORTEXM4_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM4_PRIORITY 7u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr_INTC_CORTEXM0P_PRIORITY 3u
#define BLE_bless_isr_INTC_CORTEXM4_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM4_PRIORITY 7u
#define BLE_bless_isr_INTC_NUMBER 24u

/* imuSPI_SCB_IRQ */
#define imuSPI_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define imuSPI_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define imuSPI_SCB_IRQ__INTC_NUMBER 42u
#define imuSPI_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define imuSPI_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define imuSPI_SCB_IRQ_INTC_NUMBER 42u

/* ppgI2C_SCB_IRQ */
#define ppgI2C_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ppgI2C_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ppgI2C_SCB_IRQ__INTC_NUMBER 44u
#define ppgI2C_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ppgI2C_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ppgI2C_SCB_IRQ_INTC_NUMBER 44u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
