/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_GreenLED */
#define Pin_GreenLED_0_DRIVEMODE CY_GPIO_DM_PULLUP_IN_OFF
#define Pin_GreenLED_0_INBUF_ENABLED 0u
#define Pin_GreenLED_0_INIT_DRIVESTATE 1u
#define Pin_GreenLED_0_INIT_MUXSEL 0u
#define Pin_GreenLED_0_INPUT_SYNC 2u
#define Pin_GreenLED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_GreenLED_0_NUM 7u
#define Pin_GreenLED_0_PORT GPIO_PRT11
#define Pin_GreenLED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_GreenLED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_GreenLED_DRIVEMODE CY_GPIO_DM_PULLUP_IN_OFF
#define Pin_GreenLED_INBUF_ENABLED 0u
#define Pin_GreenLED_INIT_DRIVESTATE 1u
#define Pin_GreenLED_INIT_MUXSEL 0u
#define Pin_GreenLED_INPUT_SYNC 2u
#define Pin_GreenLED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_GreenLED_NUM 7u
#define Pin_GreenLED_PORT GPIO_PRT11
#define Pin_GreenLED_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_GreenLED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
