/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* mSPI_ss0_m */
#define mSPI_ss0_m_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define mSPI_ss0_m_0_INBUF_ENABLED 0u
#define mSPI_ss0_m_0_INIT_DRIVESTATE 1u
#define mSPI_ss0_m_0_INIT_MUXSEL 20u
#define mSPI_ss0_m_0_INPUT_SYNC 2u
#define mSPI_ss0_m_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mSPI_ss0_m_0_NUM 3u
#define mSPI_ss0_m_0_PORT GPIO_PRT10
#define mSPI_ss0_m_0_SLEWRATE CY_GPIO_SLEW_FAST
#define mSPI_ss0_m_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define mSPI_ss0_m_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define mSPI_ss0_m_INBUF_ENABLED 0u
#define mSPI_ss0_m_INIT_DRIVESTATE 1u
#define mSPI_ss0_m_INIT_MUXSEL 20u
#define mSPI_ss0_m_INPUT_SYNC 2u
#define mSPI_ss0_m_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mSPI_ss0_m_NUM 3u
#define mSPI_ss0_m_PORT GPIO_PRT10
#define mSPI_ss0_m_SLEWRATE CY_GPIO_SLEW_FAST
#define mSPI_ss0_m_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* mSPI_miso_m */
#define mSPI_miso_m_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define mSPI_miso_m_0_INBUF_ENABLED 1u
#define mSPI_miso_m_0_INIT_DRIVESTATE 1u
#define mSPI_miso_m_0_INIT_MUXSEL 20u
#define mSPI_miso_m_0_INPUT_SYNC 2u
#define mSPI_miso_m_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mSPI_miso_m_0_NUM 1u
#define mSPI_miso_m_0_PORT GPIO_PRT10
#define mSPI_miso_m_0_SLEWRATE CY_GPIO_SLEW_FAST
#define mSPI_miso_m_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define mSPI_miso_m_DRIVEMODE CY_GPIO_DM_HIGHZ
#define mSPI_miso_m_INBUF_ENABLED 1u
#define mSPI_miso_m_INIT_DRIVESTATE 1u
#define mSPI_miso_m_INIT_MUXSEL 20u
#define mSPI_miso_m_INPUT_SYNC 2u
#define mSPI_miso_m_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mSPI_miso_m_NUM 1u
#define mSPI_miso_m_PORT GPIO_PRT10
#define mSPI_miso_m_SLEWRATE CY_GPIO_SLEW_FAST
#define mSPI_miso_m_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* mSPI_mosi_m */
#define mSPI_mosi_m_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define mSPI_mosi_m_0_INBUF_ENABLED 0u
#define mSPI_mosi_m_0_INIT_DRIVESTATE 1u
#define mSPI_mosi_m_0_INIT_MUXSEL 20u
#define mSPI_mosi_m_0_INPUT_SYNC 2u
#define mSPI_mosi_m_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mSPI_mosi_m_0_NUM 0u
#define mSPI_mosi_m_0_PORT GPIO_PRT10
#define mSPI_mosi_m_0_SLEWRATE CY_GPIO_SLEW_FAST
#define mSPI_mosi_m_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define mSPI_mosi_m_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define mSPI_mosi_m_INBUF_ENABLED 0u
#define mSPI_mosi_m_INIT_DRIVESTATE 1u
#define mSPI_mosi_m_INIT_MUXSEL 20u
#define mSPI_mosi_m_INPUT_SYNC 2u
#define mSPI_mosi_m_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mSPI_mosi_m_NUM 0u
#define mSPI_mosi_m_PORT GPIO_PRT10
#define mSPI_mosi_m_SLEWRATE CY_GPIO_SLEW_FAST
#define mSPI_mosi_m_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* mSPI_sclk_m */
#define mSPI_sclk_m_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define mSPI_sclk_m_0_INBUF_ENABLED 0u
#define mSPI_sclk_m_0_INIT_DRIVESTATE 1u
#define mSPI_sclk_m_0_INIT_MUXSEL 20u
#define mSPI_sclk_m_0_INPUT_SYNC 2u
#define mSPI_sclk_m_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mSPI_sclk_m_0_NUM 2u
#define mSPI_sclk_m_0_PORT GPIO_PRT10
#define mSPI_sclk_m_0_SLEWRATE CY_GPIO_SLEW_FAST
#define mSPI_sclk_m_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define mSPI_sclk_m_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define mSPI_sclk_m_INBUF_ENABLED 0u
#define mSPI_sclk_m_INIT_DRIVESTATE 1u
#define mSPI_sclk_m_INIT_MUXSEL 20u
#define mSPI_sclk_m_INPUT_SYNC 2u
#define mSPI_sclk_m_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define mSPI_sclk_m_NUM 2u
#define mSPI_sclk_m_PORT GPIO_PRT10
#define mSPI_sclk_m_SLEWRATE CY_GPIO_SLEW_FAST
#define mSPI_sclk_m_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
